stepbystep.progress.*:
  type: config_object
  label: 'Step by Step progress'
  mapping:
    progress:
      type: sequence
      label: 'Progress'
      sequence:
        type: string
        label: 'Status'
