<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 * From Drupal.org -> "If a module wishes to act on the rendered HTML of the entity rather than the structured content array, it may use this hook to add a #post_render callback."
*/
function usagov_header_hooks_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  usagov_header_hooks_remove_shortlink($build);
  usagov_header_hooks_modify_canonical_link($build);
}

function usagov_header_hooks_remove_shortlink(array &$attachments) {
  if (!isset($attachments['#attached']['html_head_link'])) {
    return;
  }

  foreach ($attachments['#attached']['html_head_link'] as $key => $value) {
    if (isset($value[0]['rel']) && $value[0]['rel'] == 'shortlink') {
      unset($attachments['#attached']['html_head_link'][$key]);
    }
  }
}

function usagov_header_hooks_modify_canonical_link(array &$attachments) {
  if (!isset($attachments['#attached']['html_head_link'])) {
    return;
  }
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    foreach ($attachments['#attached']['html_head_link'] as $key => $value) {
      if (isset($value[0]['rel']) && $value[0]['rel'] == 'canonical') {
        $href = $attachments['#attached']['html_head_link'][0][0]['href'];
        if (str_ends_with($href, '/node/1')) {
          $attachments['#attached']['html_head_link'][0][0]['href'] = substr($href, 0, -7) . "/";
        }
      }
    }
  }
}

/**
 * Implements hook_page_attachments_alter.
 * We just want to add / to the alternate links on the home pages.
 */
function usagov_header_hooks_page_attachments_alter(array &$attachments) {
  if (!isset($attachments['#attached']['html_head_link'])) {
    return;
  }
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    foreach ($attachments['#attached']['html_head_link'] as $key => $links) {
      $modified_links = [];
      foreach ($links as $link) {
        if (($link['rel'] == "alternate") && !str_ends_with($link['href'], '/')) {
          $link['href'] .= "/";
        }
        $modified_links[] = $link;
      }
      $attachments['#attached']['html_head_link'][$key] = $modified_links;
    }
  }
}
