# orphaned_entities.settings:
#   type: config_object
#   label: 'Orphaned Entities Settings'
#   mapping:
#     policy_library:
#       type: mapping
#       mapping:
#         custom_module_settings:
#           type: text
#           label: 'Custom module settings'
