<?php

/**
 * @file
 */

use Drupal\node\Entity\Node;

/**
* Toogle State Form ID
*/
function get_static_state_form_id() {
  return 'toggle_static_site_generation_form';
}

/**
* Toogle State Form Button Name
*/
function get_static_state_button_name() {
  return 'confirm_toggle';
}

/**
 * Toggle State variable name for sset/sget/sdel
 */
function get_static_state_var() {
  return 'usagov.tome_run_disabled';
}

/**
  * Implements hook_form_alter().
  */
function usagov_directories_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == get_static_state_form_id()) {
    $toggle_state = \Drupal::state()->get(get_static_state_var()) ? 1 : 0;
    $form_state->setValue(get_static_state_button_name(),$toggle_state ? TRUE : FALSE);
    //$form_state['values'][get_static_state_button_name()] = TRUE;
    \Drupal::logger('usagov_directories')->notice(
      t("Tome state var: @toggle_state", ["@toggle_state"=>$toggle_state]));
  }
}

/**
 * Implements hook_views_pre_render()
 */
function usagov_directories_views_pre_render($view) {
  if ($view->id() == 'federal_agencies' && $view->current_display == 'block_1') {

    $new_result = $view->result;
    for ($res = 0; $res < count($new_result); $res++) {
      $nid = $new_result[$res]->_entity->nid[0]->value;
      $node = Node::load($nid);
      $node_title = $node->get('title')[0]->value;

      $type_str = $new_result[$res]->_entity->type[0]->target_id;
      if ($type_str == "agency_synonym") {
        $pid_str = $new_result[$res]->_entity->field_agency_reference->target_id;
        // Need this check in case synonyms were not backlinked to their directory.
        if ($pid_str) {
          $parent = Node::load($pid_str);
          $new_result[$res]->_entity = clone $parent;
          $new_result[$res]->_entity->title[0]->value = $node_title;
        }

      }
    }

    $view->result = $new_result;
  }
}
