<?php

use Drupal\Core\Url;
use Drupal\usagov_wizard\MenuChecker;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Alter the form by adding a "View Term" button
 * if the form is the taxonomy_term_wizard_form.
 */
function usagov_wizard_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'taxonomy_term_wizard_form') {
    if (isset($form['tid'])) {
      $form['actions']['link_to_term'] = [
        '#title' => t('View Term'),
        '#type' => 'link',
        '#url' => Url::fromUri('base:/taxonomy/term/' . $form['tid']["#value"]),
        '#attributes' => [
          'class' => [
            'button',
            'usa-button'
          ],
        ],
        '#weight' => 10,
      ];
    }
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function usagov_wizard_theme_suggestions_page_alter(array &$suggestions, array &$variables) {
$taxonomy_term = \Drupal::routeMatch()->getParameter('taxonomy_term');
  if ($taxonomy_term instanceof \Drupal\taxonomy\Entity\Term) {
    $suggestions[] = 'page__taxonomy__term__' . $taxonomy_term->vid->getValue()[0]['target_id'];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Preprocess the page by retrieving information about the taxonomy term,
 * checking its parent terms, and matching it with menu entities.
 * The matched menu entities are then sorted by weight and added to the page variables.
 */
function usagov_wizard_preprocess_page(&$variables) {
  $taxonomy_term = \Drupal::routeMatch()->getParameter('taxonomy_term');
  if ($taxonomy_term instanceof \Drupal\taxonomy\Entity\Term) {
    $menuChecker = \Drupal::classResolver(MenuChecker::class);

    // Get an array of the current taxonomy term and all of its parents.
    $termParents = $menuChecker->getTermParents($taxonomy_term);
    if ($variables['language']->getId() == 'en') {
      $menu_name = 'left-menu-english';
    } else {
      $menu_name = 'left-menu-spanish';
    }

    // Check the provided $menu_name for links to taxonomy terms.
    $menuEntities = $menuChecker->getTargetEntities($menu_name);

    // See if there are any matches.
    $matching_tid = array_intersect($termParents, $menuEntities['target_tids']);
    $matching_tid = implode(',', $matching_tid);

    // If there are matches, send them to the twig.
    if (isset($matching_tid)) {
      foreach ($menuEntities['menu_entities'] as $menuEntity) {
        $entities = array_map(function($menuEntity) {
          return [
            'label' => $menuEntity->title->value,
            'link' => Url::fromUri($menuEntity->link->uri)->toString(),
            'weight' => $menuEntity->getWeight(),
          ];
        }, $menuEntities['menu_entities']);

        usort($entities, function($item1, $item2) {
          return $item1['weight'] <=> $item2['weight'];
        });

        $variables['menu_entities'] = $entities;
      }
    }
  }
}
