<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\block\Entity\Block;


/**
 * Implements hook_entity_insert() and hook_entity_update().
 */
function usagov_emergency_banner_entity_insert(EntityInterface $entity) {
    usagov_emergency_banner_place_block($entity);
}

function usagov_emergency_banner_entity_update(EntityInterface $entity) {
    $block = Block::load('some_alert');
    $block->setRegion('above_header');
    $block->save();

    usagov_emergency_banner_place_block($entity);
}

/**
 * Places the block above the header if the checkbox is checked.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function usagov_emergency_banner_place_block(EntityInterface $entity) {


    if ($entity->bundle() === 'emergency_banner' ) {
        // $place_above_header = $entity->get('field_place_above_header')->value;

        // Load or create the block placement entity.

        // if ($place_above_header) {
        //     $block->setRegion('above_header');
        //     $block->save();
        // } else {
        //     // If the checkbox is unchecked, remove the block placement.
        //     if ($block) {
        //         $block->setRegion('');
        //         $block->save();
        //     }
        // }
    }
}