#!/bin/env bash

source ~/.profile &> /dev/null

# Get local env
. /opt/callcenter/env.local

waitTimeFile="waittime.json"

echo "Getting access token."
tokenResponse=$(curl -X POST https://login.$CALL_CENTER_ENVIRONMENT/oauth/token -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=client_credentials&client_id=$CALL_CENTER_CLIENT_ID&client_secret=$CALL_CENTER_CLIENT_SECRET")
token=$(echo "$tokenResponse" | jq -r '.access_token')

echo "Getting en wait time."
enWaitTime=$(curl -X GET https://api.$CALL_CENTER_ENVIRONMENT/api/v2/routing/queues/$CALL_CENTER_EN_QUEUE_ID/estimatedwaittime -H "Authorization:Bearer $token" | jq -r '.results[].estimatedWaitTimeSeconds');

echo "Getting sp wait time."
spWaitTime=$(curl -X GET https://api.$CALL_CENTER_ENVIRONMENT/api/v2/routing/queues/$CALL_CENTER_SP_QUEUE_ID/estimatedwaittime -H "Authorization:Bearer $token" | jq -r '.results[].estimatedWaitTimeSeconds');

combinedWaitTimes='{ "enEstimatedWaitTimeSeconds": '$enWaitTime',
  "spEstimatedWaitTimeSeconds": '$spWaitTime'}'

echo "Setting wait time file."
echo "$combinedWaitTimes" > $waitTimeFile

# # Upload file to S3 bucket
echo "uploading waittime.json to S3."
aws_cp waittime.json s3://$S3_BUCKET/cms/public/waittime.json
