services:
  cms:
    container_name: cms
    image: gsatts/usagov-2021:cms-latest
    build:
      context: ./
      dockerfile: .docker/Dockerfile-cms
      args:
        - BUID
        - BGID
        - HOST_ARCH
        - BUILD_ENV
    ports:
      - 80:80
      - 443:443
    networks:
      gsa-gov:
        aliases:
          - beta-local-usagov.apps.internal
          - cms-local-usagov.apps.internal
          - beta-usagov.docker.local
          - cms-usagov.docker.local
    volumes:
      - .:/var/www:delegated
      - ./.docker/src-cms/etc/periodic/1min/generate-static-site:/etc/periodic/1min/generate-static-site:delegated
      - ./.docker/src-cms/50_xdebug.ini:/etc/php83/conf.d/50_xdebug.ini:delegated
    env_file:
      - ./env.local
    security_opt:
      - apparmor:docker-default
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 64GB
          cpus: "8.0"
          pids: 256
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      WWW_HOST: beta-local-usagov.apps.internal
      CF_INSTANCE_INDEX: '1'
      FIX_FILE_PERMS:
      VCAP_APPLICATION: >
        {"name":"cms", "application_id":"docker", "space_name":"local", "application_uris":["beta-local-usagov.apps.internal","cms-local-usagov.apps.internal"]}
      VCAP_SERVICES: >
        { "s3": [{
            "name": "storage",
            "credentials": {
              "access_key_id": "minioadmin",
              "secret_access_key": "miniopass",
              "region": "us-west-1",
              "bucket": "local",
              "fips_endpoint": "minio:9000",
              "endpoint": "minio:9000"
               }
             },
             {
               "credentials": {
                 "access_key_id": "REPLACE_THIS_IF_YOU_NEED_TO_WRITE_TO_THE_BUCKET",
                 "additional_buckets": [],
                 "bucket": "cg-c4ae21db-2fd9-4501-bce8-549dc06ab668",
                 "endpoint": "s3-fips.us-gov-west-1.amazonaws.com",
                 "fips_endpoint": "s3-fips.us-gov-west-1.amazonaws.com",
                 "insecure_skip_verify": false,
                 "region": "us-gov-west-1",
                 "secret_access_key": "REPLACE_THIS_IF_YOU_NEED_TO_WRITE_TO_THE_BUCKET"
               },
               "instance_name": "s3forAnalyticsReporter",
               "label": "s3",
               "name": "s3forAnalyticsReporter",
               "tags": [
                 "AWS",
                 "S3",
                 "object-storage"
               ]
            }
          ],
          "aws-rds": [{
            "name": "database",
            "credentials": {
              "db_name": "drupal",
              "host": "database",
              "password": "mysql",
              "port": "3306",
              "username": "root"
            }
          }],
          "user-provided": [{
            "name": "secrets",
            "credentials": {
              "ADMIN_EMAIL": "secret@example.com",
              "CRON_KEY": "SECRET",
              "HASH_SALT": "SECRET",
              "ROOT_USER_NAME": "root",
              "ROOT_USER_PASS": "root"
            }
          },
          {
            "name": "secauthsecrets",
            "credentials": {
              "SPKEY": "SPKey",
              "SPCRT": "SPCert"
            }
          }],
         "aws-elasticache-redis": [
          {
            "credentials": {
              "current_redis_engine_version": "6.2",
              "host": "cache",
              "hostname": "cache",
              "password": "CACHE_SERVICE_PASSWORD_FOR_LOCAL_DEV",
              "port": "6379",
              "uri": "redis://:CACHE_SERVICE_PASSWORD_FOR_LOCAL_DEV@cache:6379",
              "IS_LOCAL_DEV": 1
            },
            "name": "cache-service",
            "tags": [
                        "redis",
                        "Elasticache",
                        "AWS",
                        "cache-service"
                ]
          }
        ]
        }
    depends_on:
      - database
      - minio
      - cache

  database:
    container_name: database
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - .:/app:delegated
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: drupal
    cap_add:
      - SYS_NICE
    networks:
      - gsa-gov

  minio:
    container_name: minio
    build:
      context: ./
      dockerfile: .docker/Dockerfile-minio
      args:
        - BUILD_ENV
    # ports:
    #   - 9000:9000
    #   - 9001:9001
    volumes:
      - ./s3:/data
      - ./.docker/src-minio/docker-entrypoint-minio.sh:/docker-entrypoint-minio.sh
      - ./.docker/src-minio/setup-bucket.sh:/setup-bucket.sh
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniopass
      - MINIO_SERVER_URL=https://127.0.0.1:9000
      - MINIO_DOMAIN=minio
    networks:
      gsa-gov:
        aliases:
          - local.minio

  cypress:
    container_name: cypress
    build:
      context: ./
      dockerfile: .docker/Dockerfile-cypress
    env_file:
      - ./env.local
      - ./env.local.cypress
    volumes:
      - ./automated_tests/e2e-cypress:/app/e2e-cypress
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app/e2e-cypress
    command: /app/start.sh
    networks:
      - gsa-gov

  composer:
    container_name: composer
    build:
      context: ./
      dockerfile: .docker/Dockerfile-cms
      target: composer-builder
      args:
        - BUID
        - BGID
        - GITCOMMIT
        - GITBRANCH
        - GITTAG
        - BUILD_ENV
    command: echo "Shutting Down on Purpose"
    volumes:
      - .:/var/www:delegated
    env_file:
      - ./env.local

  node:
    container_name: node
    build:
      context: ./
      dockerfile: .docker/Dockerfile-cms
      target: theme-builder
      args:
        - BUID
        - BGID
    command: npm run watch --prefix /var/www/web/themes/custom/usagov
    volumes:
      - .:/var/www:delegated
    env_file:
      - ./env.local
    networks:
      - gsa-gov

  cache:
    container_name: cache
    build:
      dockerfile: .docker/Dockerfile-cache
    ports:
      - 6379:6379
    networks:
      - gsa-gov

volumes:
  database_data:
#   nfsmount:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,fsc,actimeo=2,tcp
#       device: ":${PWD}"

networks:
  gsa-gov:
