#!/usr/bin/env bash

### Test Setup: create several dummy PID files in the lock directory:
mkdir /tmp/tasks/run/task-lock-reference-script
touch /tmp/tasks/run/task-lock-reference-script/{787878,878787,908789}

### Attempt to run 
scripts/cron/task-lock-reference-script &
sleep 5
echo
touch /tmp/tasks/run/task-lock-reference-script/{898098,908809,907890}
scripts/cron/task-lock-reference-script &
sleep 5
echo
scripts/cron/task-lock-reference-script
echo
sleep 6
scripts/cron/task-lock-reference-script
echo
