#!/usr/bin/env bash

SCRIPT_ROOT=scripts/cron # on the container, change this path to /opt/cron/ as we'll copy these in the dockerfile
RUN_ROOT=/tmp/tasks/run  # on the container, maybe this should be /var/run?

### Test Setup: create several dummy PID files in the lock directory:
mkdir $RUN_ROOT/task-lock-reference-script
touch $RUN_ROOT/task-lock-reference-script/{787878,878787,908789}

### Attempt to run concurrently
$SCRIPTS_ROOT/task-lock-reference-script &
sleep 5
echo
touch $RUN_ROOT/task-lock-reference-script/{898098,908809,907890}
$SCRIPTS_ROOT/task-lock-reference-script &
sleep 5
echo
$SCRIPTS_ROOT/task-lock-reference-script
echo
sleep 6
$SCRIPTS_ROOT/task-lock-reference-script
echo
