<?php

/**
 * Implements hook_theme().
 */
function usagov_menus_theme($existing, $type, $theme, $path) {
  return [
    'usagov_menu_mobile' => [
      'variables' => [
        'main_nav_items' => NULL,
        'node' => NULL,
        'translations' => NULL,

        'active_trail' => NULL,
        'found_active_item' => NULL,
        'active_item_has_children' => NULL,
        'sibblings_of_active_item' => NULL,
        'submenu' => NULL,

        'depth' => NULL,
        'current' => NULL,
      ],
    ],
    'usagov_menu_sidebar' => [
      'variables' => [
        'start_item' => NULL,
        'items' => NULL,
        'depth' => NULL,
        'current_item_title' => NULL,
        'page_type_is' => NULL,
        'nav_aria_label' => NULL,
        'current' => NULL,
        'is_spanish_menu' => NULL,
        'leaf' => NULL,
      ],
    ],
  ];
}
