name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrates how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
core_version_requirement: ^8.8 || ^9
dependencies:
  - 'drupal:block'
  - 'drupal:views'
  - 'webform:webform'
  - 'webform:webform_node'

# Information added by Drupal.org packaging script on 2021-05-05
version: '6.0.3'
project: 'webform'
datestamp: 1620250261
