webform_group.settings:
  type: config_object
  label: 'Webform group settings'
  mapping:
    mail:
      type: mapping
      label: 'Email settings'
      mapping:
        group_owner:
          type: boolean
          title: Allow group owner to be emailed.
        group_roles:
          type: sequence
          label: Group roles
          sequence:
            type: string
            label: Group role
