<?php

use Drupal\block\Entity\Block;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert() and hook_entity_update().
 */
function usagov_alert_block_content_insert(EntityInterface $entity) {
  usagov_alert_place_block($entity);
}

function usagov_alert_block_content_update(EntityInterface $entity) {
  usagov_alert_place_block($entity);
}

/**
 * Places the block above the header if the checkbox is checked.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function usagov_alert_place_block(EntityInterface $entity) {

  if ($entity->bundle() === 'emergency_banner') {

    $place_above_header = $entity->field_place_above_header->value;
    // var_dump($entity);
    // die($entity->id());
    // Load or create the block placement entity.
    if ($place_above_header && $entity->getEntityTypeId() == 'block_content') {
      // If the checkbox is checked, the block is placed above the header.
      // $id = $entity->id();
      // $id = 'usagov_welcomeblock';
      // $block = Block::load($id);

      // $block->setRegion('header_top');
      // $block->save();

      // if ($block) {
      //   $block->setRegion('header_top');
      //   $block->save();
      // }
      // else{
      //   \Drupal::logger('usagov_alert')->error('Block with ID @id could not be loaded.', ['@id' => $id]);
      // }

    }
    else {
      // If the checkbox is unchecked, remove the block placement.
      // if ($block) {
      //   $block->setRegion('');
      //   $block->save();
      // }
    }
  }
}
