content_lock_timeout.settings:
  type: config_object
  mapping:
    content_lock_timeout_minutes:
      type: string
      label: 'Break lock stale'
    content_lock_timeout_on_edit:
      type: integer
      label: 'Break lock on edit'
