<?php

/**
 * @file
 * Hooks related to AI Chatbot.
 */

use Drupal\Core\Url;

/**
 * @addtogroup hooks
 * @{
 */

/**
 * Alter the Deepchat rendering array.
 *
 * Read more about it in https://deepchat.dev/docs/styles.
 *
 * @param array $deepchat_settings
 *   The array as its being user for attributes on the Deepchat tag.
 */
function usagov_chatbot_deepchat_settings(array &$deepchat_settings) {
  $deepchat_settings['style'] = 'border: none;';
}

/**
 * Alter the Deepchat buttons.
 *
 * These are buttons that are set after each assistant message, and can be
 * things like copy, like, dislike, etc.
 *
 * @param array $buttons
 *   The buttons array, passed by reference.
 */
function usagov_chatbot_deepchat_buttons_alter(array &$buttons) {

}

/**
 * Prepend any outgoing messages from the AI Assistant.
 *
 * @param string $message
 *   The message to be sent.
 * @param string $type
 *   The type of message (text/html).
 * @param string $assistant_id
 *   The assistant id.
 * @param string $thread_id
 *   The thread id.
 *
 * @return string
 *   The message to be prepended.
 */
function usagov_chatbot_deepchat_prepend_message($message, $type, $assistant_id, $thread_id) {
  return "Did you like this message?";
}
