# Configuration for redis container for LOCAL DEV ONLY.
maxmemory 2gb

# Configuring redis as a cache
maxmemory-policy volatile-lru

# Set a password (must match what's in docker-compose.yml)
requirepass CACHE_SERVICE_PASSWORD_FOR_LOCAL_DEV

# By default, TLS/SSL is disabled. To enable it, the "tls-port" configuration
# directive can be used to define TLS-listening ports. To enable TLS on the
# default port, use:
#
port 0
tls-port 6379

# Configure a X.509 certificate and private key to use for authenticating the
# server to connected clients, masters or cluster peers.  These files should be
# PEM formatted.
#
#### Note that redis_dev.crt  must also be provided to the cms ####
tls-cert-file /etc/redis/redis_dev.crt
tls-key-file /etc/redis/redis_dev.key

# Configure a CA certificate(s) bundle or directory to authenticate TLS/SSL
# clients and peers.  Redis requires an explicit configuration of at least one
# of these, and will not implicitly use the system wide configuration.
#
tls-ca-cert-dir /etc/ssl/certs

# By default, clients (including replica servers) on a TLS port are required
# to authenticate using valid client side certificates.
#
# If "no" is specified, client certificates are not required and not accepted.
# If "optional" is specified, client certificates are accepted and must be
# valid if provided, but are not required.
#
tls-auth-clients optional

# For more, see https://github.com/redis/redis/blob/6.2/redis.conf