# Configuration for redis container for LOCAL DEV ONLY.
maxmemory 2gb

# Configuring redis as a cache
maxmemory-policy volatile-lru

# Set a password (must match what's in docker-compose.yml)
requirepass CACHE_SERVICE_PASSWORD_FOR_LOCAL_DEV

# For more, see https://github.com/redis/redis/blob/6.2/redis.conf
