<?php

/**
 * @file
 * Call classes.
 */

// use Drupal\user\Entity\User;
// use Drupal\user\Entity\Role;

// /**
//  * Update the content notification logic.
//  */
// function usa_content_moderation_notifications_mail_alter(&$message) {
//   $currentuser = User::load(\Drupal::currentUser()->id());
//   $hasPermission = $currentuser->hasPermission('Self content notification');
//   $message['to'] = \Drupal::config('system.site')->get('mail');

//   if ($hasPermission) {
//     $message['to'] = $currentuser->getEmail();
//     unset($message['headers']['Bcc']);
//   }
// }


/**
 * Implements hook_theme_suggestions_page() to set 40x template suggestions
 */
function usa_404_theme_suggestions_page(array $variables) {
  $path_args = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
  $route_name = \Drupal::routeMatch()->getRouteName();
  
  dpm(theme_get_suggestions($path_args, 'page'));
  // dpm(\Drupal::service('path.current')->getPath());
  dpm(explode('/', trim(\Drupal::service('path.current')->getPath(), '/')));
  dpm(\Drupal::routeMatch()->getRouteName());
  dpm($variables);
}