#!/bin/env bash

SPACE=${1:-dr}

source ~/.profile $SPACE &> /dev/null

DATEFILE=logs.lastrun
rm -f /tmp/$DATEFILE
aws_cp  s3://$S3_BUCKET/cfevents/${SPACE}/$DATEFILE /tmp/ &>/dev/null
if [ -f /tmp/$DATEFILE ]; then
    CFEVENTS_LASTRUN=$(TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ" -r /tmp/$DATEFILE)
else
    CFEVENTS_LASTRUN=$(TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ" -d "2 months ago")
fi

touch /tmp/$DATEFILE
CFEVENTS_THISRUN=$(TZ=UTC date +"%Y-%m-%dT%H%M%SZ" -r /tmp/$DATEFILE)
/opt/cfevents/get-events $SPACE $CFEVENTS_LASTRUN | tee /tmp/cfevents.${CFEVENTS_THISRUN}.log

aws_cp  /tmp/$DATEFILE s3://$S3_BUCKET/cfevents/${SPACE}/
aws_cp  /tmp/cfevents.${CFEVENTS_THISRUN}.log s3://$S3_BUCKET/cfevents/${SPACE}/
