#!/bin/sh
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 11: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 12: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 13: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 14: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 15: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 16: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 17: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 18: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 19: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 20: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 21: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 22: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 23: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 24: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 25: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 26: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 27: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 28: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 29: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 20: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 31: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 32: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 33: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 34: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 35: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 36: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 37: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 38: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 39: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 40: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 41: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 42: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 43: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 44: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 45: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 46: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 47: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 48: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 49: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 50: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 51: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 52: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 53: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 54: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 55: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 56: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 57: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 58: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 59: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 60: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 61: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 62: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 63: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 64: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 65: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 66: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 67: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 68: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 69: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 70: I finished\n" localhost &