map $uri $blog_usa_uri {
# TODO: this is just an example. We'll get the full list by using the old magics.
/enhancing-the-publics-experience-with-government-in-2024   /blog/2025/01/enhancing-the-publics-experience-with-government-in-2024 ;
}
