<?php

/**
 * @file
 * Primary module hooks for USAgov Login Customization module.
 *
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function usagov_login_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $config = \Drupal::config('usagov_login.settings');
  $loginPath = $config->get('sso_login_path');
  $loginText = $config->get('sso_login_text');

  # allow override for local login forms via drush sset, or $settings[] in settings.local.php
  $state = \Drupal::state()->get('usagov_login_local_form', 0);
  $settings_state = Settings::get('usagov_login_local_form');
  if ($settings_state || $state) {
    $state = 1;
  }

  if ($loginPath) {

    if (!$state) {
      $form['name']['#access'] = FALSE;
      $form['pass']['#access'] = FALSE;
      $form['actions']['#access'] = FALSE;
    }

    $form['sso_button'] = [
      '#type' => 'html_tag',
      '#tag' => 'a',
      '#attributes' => [
        'href' => $loginPath,
        'class' => ['usa-button'],
      ],
      '#value' => $loginText,
      '#weight' => '-20',
    ];
    #$form['#prefix'] = '<div class="usa-list.usa-list--unstyled">';
    #$form['#suffix'] = '</div>';
    $form['#attributes']['class'] = 'usa-list.usa-list--unstyled';
  }
}
