
### TBD: Use a more determinate tag please
FROM ubuntu:latest

ARG GITBRANCH
ENV GITBRANCH ${GITBRANCH:-none}

ARG GITCOMMIT
ENV GITCOMMIT ${GITCOMMIT:-none}

ARG GITTAG
ENV GITTAG ${GITTAG:-none}

ARG CONTAINERTAG
ENV CONTAINERTAG ${CONTAINERTAG:-none}

ARG BUID=1000
ARG BGID=1000

RUN apt update --allow-unauthenticated \
    && apt-get -y install --no-install-recommends ca-certificates pv openssh-client sshpass wget gnupg2 \
    && wget --user-agent="Mozilla" --no-check-certificate -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add - \
    && echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list \
    && apt update \
    && apt-get -y install \
    ca-certificates \
    cf8-cli \
    xz-utils \
    cron \
    cronutils \
    inotify-tools \
    curl \
    jq \
    moreutils \
    less \
    pv \
    tar \
    vim \
    nano \
    unzip \
    && rm -rf /var/lib/apt/lists/*

ADD https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip /root/awscliv2.zip
RUN unzip /root/awscliv2.zip -d /root/
RUN /root/aws/install
RUN rm -rf /root/aws /root/awscliv2.zip

COPY .docker/src-cron/etc /etc
COPY .docker/src-cron/opt /opt

COPY bin/cloudgov/events/get-events /opt/cron/
COPY .docker/src-cron/root/.profile /root/

ARG S6_VERSION
#ENV S6_VERSION ${S6_VERSION:-v2.2.0.3}
ENV S6_VERSION ${S6_VERSION:-v3.2.0.0}

ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-x86_64.tar.xz        /tmp/s6-overlay.tar.xz
#ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-symlinks-arch.tar.xz /tmp/s6-overlay-symlinks.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-noarch.tar.xz        /tmp/s6-overlay-noarch.tar.xz

#ADD https://github.com/just-containers/s6-overlay/releases/download/v3.2.0.0/s6-overlay-x86_64.tar.xz /root/s6overlay.tar.xz
#ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz /root/s6overlay.tar.gz
#RUN mkdir -p /root/s6/
#RUN tar xzf /root/s6overlay.tar.gz -C /root/s6/
#RUN tar xxf /root/s6overlay.tar.xz -C /

RUN tar -C / -Jxpf /tmp/s6-overlay.tar.xz
#RUN tar -C / -Jxpf /tmp/s6-overlay-symlinks.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz

HEALTHCHECK CMD s6-svstat /var/run/s6/services/cron

#CMD ["/init"]
ENTRYPOINT ["/init"]
