
###############################################################
FROM alpine:3.20 AS www

ARG S6_VERSION
ENV S6_VERSION=${S6_VERSION:-v2.2.0.3}

ARG GITBRANCH
ENV GITBRANCH=${GITBRANCH:-none}

ARG GITCOMMIT
ENV GITCOMMIT=${GITCOMMIT:-none}

ARG GITTAG
ENV GITTAG=${GITTAG:-none}

ARG CONTAINERTAG
ENV CONTAINERTAG=${CONTAINERTAG:-none}

ARG BUID=1000
ARG BGID=1000

ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz /tmp/s6overlay.tar.gz

# Dependencies
RUN sed -E -i "s/:x:${BUID}:/:x:1919:/g" /etc/passwd \
  && sed -E -i "s/:x:([0-9]+):${BGID}:/:x:\1:1919:/g" /etc/passwd \
  && sed -E -i "s/:x:${BGID}:/:x:1919:/g" /etc/group \
  && sed -E -i "s/nginx:x:[0-9]+:[0-9]+:/nginx:x:${BUID}:${BGID}:/g" /etc/passwd \
  && sed -E -i "s/nginx:x:[0-9]+:/nginx:x:${BGID}:/g" /etc/group \
  && addgroup -S -g $BGID nginx \
  && adduser -S -G nginx -D -H -u $BUID nginx \
  && apk upgrade --update \
  && apk add --no-cache --virtual .persistent-deps \
    ca-certificates \
    curl \
    gettext \
    git \
    inotify-tools \
    jq \
    moreutils \
    pv \
    openssl \
    tar \
    xz \
    vim \
    nano \
    nginx \
    nginx-mod-http-lua \
  && mkdir -p /var/www/web/sites/default/files \
  # s6 supervisor setup
  && tar xzf /tmp/s6overlay.tar.gz -C / \
  && rm /tmp/s6overlay.tar.gz \
  && mkdir -p /var/run/s6 \
  && chown -R nginx:nginx /var/run/s6 \
  # webserver setup
  && mkdir -p /var/www/ \
  && chown -R nginx:nginx /var/www \
  && mkdir -p /var/log/nginx \
  && chown -R nginx:nginx /var/log/nginx \
  && ln -s /dev/stderr /var/log/nginx/error.log \
  && ln -s /dev/stdout /var/log/nginx/access.log \
  && mkdir -p /run/nginx/ \
  && touch /run/nginx/nginx.pid

  # cron setup
RUN mkdir -p /etc/periodic/1min \
  && echo "*    *       *       *       *       run-parts /etc/periodic/1min" >> /etc/crontabs/root \
  # cleanup
  && rm -rf /var/cache/apk/*

ENV PATH=/var/www/vendor/bin:$PATH

COPY .docker/src-www/etc /etc
COPY .docker/motd /etc/motd
COPY --chown=nginx:nginx scripts /var/www/scripts
COPY --chown=nginx:nginx config /var/www/config
COPY --chown=nginx:nginx patches /var/www/patches
COPY --chown=nginx:nginx webroot /var/www/webroot

# Add the zscaler certificate to the trusted certs only on local builds
# COPY cannot be conditional, but RUN can run conditional code.
COPY .docker/zscaler_cert.pem /tmp/zscaler.crt
RUN if [ x"${BUILD_ENV}" = x"LOCAL" ] ; then cp /tmp/zscaler.crt /usr/local/share/ca-certificates/zscaler.crt ; update-ca-certificates ; fi

RUN chmod -R +x /etc/periodic \
  && chown nginx:nginx /var/www \
  && find /var/www -not -user $(id -u nginx) -not -group $(id -g nginx) -print0 | xargs -P 0 -0 --no-run-if-empty chown --no-dereference nginx:nginx \
  && echo "    built:" $(date) >> /etc/motd \
  && echo "    branch: " $GITBRANCH >> /etc/motd \
  && echo "    gittag: " $GITTAG >> /etc/motd \
  && echo "    commit: " $GITCOMMIT >> /etc/motd \
  && echo "    containertag: " $CONTAINERTAG >> /etc/motd \
  && echo >> /etc/motd \
  && cp /etc/motd /var/www/web/version.txt \
  && echo "PATH=$PATH" > /etc/profile.d/drupal.sh

RUN if pgrep nginx; then pkill nginx; fi

RUN apk add --no-cache gcc libc-dev make pcre-dev zlib-dev openssl-dev curl gnupg lua5.1 lua5.1-dev luajit luajit-dev libpcrecpp cmake
RUN apk del nginx nginx-mod-http-lua || true
RUN cd /tmp/ \
    && git clone --branch v0.10.26 https://github.com/openresty/lua-nginx-module.git \
    && wget https://github.com/simpl/ngx_devel_kit/archive/refs/tags/v0.3.1.tar.gz \
    && tar -xzvf v0.3.1.tar.gz \
    && mv ngx_devel_kit-0.3.1 ngx_devel_kit \
    && wget https://nginx.org/download/nginx-1.27.4.tar.gz \
    && NGCHECKSUM="3785797d3c8f96b930c11a445c68ce88b584af9645f41b8929a779ef1507b74831fa91e9144f3a56599737517cbf1864954d91e312d12cc59e23e4db72c2c716 *nginx-1.27.4.tar.gz" \
    && if [ "$(openssl sha512 -r nginx-1.27.4.tar.gz)" = "$NGCHECKSUM" ]; then \
        echo "nginx tarball checksum verification succeeded!"; \
    else \
        echo "nginx tarball checksum verification failed!"; \
        exit 1; \
    fi \
    && tar -xzvf nginx-1.27.4.tar.gz \
    && cd nginx-1.27.4 \
    && ./configure \
        --prefix=/var/lib/nginx \
        --sbin-path=/usr/sbin/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --modules-path=/usr/lib/nginx/modules \
        --with-compat \
        --with-http_gzip_static_module \
        --with-http_ssl_module \
        --with-http_realip_module \
        --with-cc-opt="-I/usr/include/luajit-2.1" \
        --with-ld-opt="-L/usr/lib -lluajit-5.1" \
        --add-module=/tmp/ngx_devel_kit \
        --add-module=/tmp/lua-nginx-module \
    && make
RUN rm /etc/nginx/modules/10_devel_kit.conf || true
RUN rm /etc/nginx/modules/30_http_lua.conf || true
RUN cd /tmp/nginx-1.27.4 \
    && make install

EXPOSE 80

WORKDIR /var/www

HEALTHCHECK CMD s6-svstat /var/run/s6/services/nginx \
  && s6-svstat /var/run/s6/services/cron \
  && s6-svstat /var/run/s6/services/cert-watcher

# Init s6
ENTRYPOINT [ "/init" ]
