ARG NGINX_VERSION="1.30.1"
FROM nginx:${NGINX_VERSION}

LABEL maintainer="USA.gov Web Ops"

ARG NGINX_VERSION=1.30.1
ARG NGINX_SHA512=a081ed49692948ea61bada05a9bade88f9899f843c8d5a72c0d5362e812c14e1ea12de729bcdfe93016323fb014681ddfa472f3352b5e83455991be715293211

ARG GITBRANCH
ENV GITBRANCH=${GITBRANCH:-none}

ARG GITCOMMIT
ENV GITCOMMIT=${GITCOMMIT:-none}

ARG GITTAG
ENV GITTAG=${GITTAG:-none}

ENV APP_NAME=USAGov \
    ANOMALY_INBOUND=5 \
    ANOMALY_OUTBOUND=4 \
    ERRORLOG=/var/log/nginx/error.log \
    LOGLEVEL=warn \
    MODSEC_DEFAULT_PHASE1_ACTION="phase:1,pass,log,tag:'\${MODSEC_TAG}'" \
    MODSEC_DEFAULT_PHASE2_ACTION="phase:2,pass,log,tag:'\${MODSEC_TAG}'" \
    MODSEC_PCRE_MATCH_LIMIT=500000 \
    MODSEC_PCRE_MATCH_LIMIT_RECURSION=500000 \
    MODSEC_REQ_BODY_ACCESS=on \
    MODSEC_REQ_BODY_LIMIT=13107200 \
    MODSEC_REQ_BODY_NOFILES_LIMIT=131072 \
    MODSEC_RESP_BODY_ACCESS=on \
    MODSEC_RESP_BODY_LIMIT=1048576 \
    MODSEC_RULE_ENGINE=on \
    MODSECURITY_ENGINE_VERSION="3.0.13" \
    MODSECURITY_NGINX_VERSION="1.0.3" \
    MODSECURITY_CRS_VERSION="4.10.0" \
    NGINX_KEEPALIVE_TIMEOUT=60s \
    PARANOIA=2 \
    PORT=80 \
    SERVERNAME=localhost \
    USER=nginx \
    WORKER_CONNECTIONS=1024

RUN apt-get update && \
    apt-get install -y \
    autoconf \
    automake \
    build-essential \
    dh-autoreconf \
    dpkg-dev \
    flex \
    gcc \
    inotify-tools \
    jq \
    libexpat1-dev \
    libgeoip-dev \
    liblmdb-dev \
    liblua5.3-dev \
    libmodsecurity-dev \
    libmodsecurity3 \
    libpcre2-dev \
    libssl-dev \
    libtool \
    libyajl-dev \
    locales \
    lua5.3-dev \
    make \
    pkg-config \
    procps \
    wget \
    zlib1g-dev

RUN set -eux; \
    mkdir /var/log/modsecurity && \
    touch /var/log/modsecurity/modsec_audit.log;

RUN cd /tmp \
    && wget https://github.com/owasp-modsecurity/ModSecurity-nginx/releases/download/v${MODSECURITY_NGINX_VERSION}/modsecurity-nginx-v${MODSECURITY_NGINX_VERSION}.tar.gz \
    && tar -xvf modsecurity-nginx-v${MODSECURITY_NGINX_VERSION}.tar.gz \
    && rm modsecurity-nginx-v${MODSECURITY_NGINX_VERSION}.tar.gz \
    && mkdir -p /opt/modsecurity-nginx-v${MODSECURITY_NGINX_VERSION} \
    && mv modsecurity-nginx-v${MODSECURITY_NGINX_VERSION}/* /opt/modsecurity-nginx-v${MODSECURITY_NGINX_VERSION}/ \
    && sed -i 's|#include <modsecurity/modsecurity.h>|#include <stdio.h>\\n#include <modsecurity/modsecurity.h>|' /opt/modsecurity-nginx-v${MODSECURITY_NGINX_VERSION}/config \
    && wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
    && echo "${NGINX_SHA512}  nginx-${NGINX_VERSION}.tar.gz" | sha512sum -c - \
    && tar -xvf nginx-${NGINX_VERSION}.tar.gz \
    && rm nginx-${NGINX_VERSION}.tar.gz \
    && mkdir -p /opt/nginx-${NGINX_VERSION} \
    && mv nginx-${NGINX_VERSION}/* /opt/nginx-${NGINX_VERSION}/ \
    && cd /opt/nginx-${NGINX_VERSION} \
    && ARGS=$(nginx -V 2>&1 | grep -oP '(?<=configure arguments: ).*?(?=--with-cc-opt)') \
    && ./configure --add-dynamic-module=../modsecurity-nginx-v${MODSECURITY_NGINX_VERSION} --with-compat $ARGS \
    && make modules \
    && cp objs/ngx_http_modsecurity_module.so /etc/nginx/modules

RUN cd /tmp \
    && wget https://github.com/coreruleset/coreruleset/releases/download/v${MODSECURITY_CRS_VERSION}/coreruleset-${MODSECURITY_CRS_VERSION}-minimal.tar.gz  \
    && tar -xvf coreruleset-${MODSECURITY_CRS_VERSION}-minimal.tar.gz \
    && rm coreruleset-${MODSECURITY_CRS_VERSION}-minimal.tar.gz \
    && mkdir -p /etc/modsecurity.d/modsecurity-crs \
    && mv coreruleset-${MODSECURITY_CRS_VERSION}/* /etc/modsecurity.d/modsecurity-crs/ \
    && mv /etc/modsecurity.d/modsecurity-crs/crs-setup.conf.example /etc/modsecurity.d/modsecurity-crs/crs-setup.conf \
    && mv /etc/modsecurity.d/modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example /etc/modsecurity.d/modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf

COPY src-waf/docker-entrypoint-waf.sh /
COPY src-waf/etc/ /etc/
COPY src-waf/opt/ /opt/
RUN rm -rf /opt/owasp-crs/tests;

COPY src-waf/opt/owasp-crs/modsecurity.conf /etc/modsecurity.d/modsecurity.conf
COPY src-waf/opt/owasp-crs/modsecurity-override.conf /etc/modsecurity.d/modsecurity-override.conf
COPY src-waf/opt/owasp-crs/setup.conf /etc/modsecurity.d/setup.conf

COPY src-waf/cert-watcher.sh /cert-watcher.sh

COPY motd /etc/motd

# Set environment variables
# When updating ZLIB_VERSION, also update ZLIB_SHA (SHA-256 of the tar.gz, published at https://www.zlib.net/)
ENV ZLIB_VERSION=1.3.2
ENV ZLIB_SHA=bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16
ENV ZLIB_SRC_URL=https://github.com/madler/zlib/releases/download/v${ZLIB_VERSION}/zlib-${ZLIB_VERSION}.tar.gz

# Warn if a newer zlib version exists
RUN LATEST=$(curl -s -o /dev/null -w "%{url_effective}" -L https://github.com/madler/zlib/releases/latest | grep -oP 'tag/v\K[^/]+') \
    && if [ "$LATEST" != "${ZLIB_VERSION}" ]; then \
        echo "WARNING: zlib ${ZLIB_VERSION} is pinned but latest release is ${LATEST}"; \
    fi

RUN wget ${ZLIB_SRC_URL} && \
    echo "${ZLIB_SHA}  zlib-${ZLIB_VERSION}.tar.gz" | sha256sum -c - && \
    tar -xvzf zlib-${ZLIB_VERSION}.tar.gz && \
    cd zlib-${ZLIB_VERSION} && \
    ./configure --prefix=/usr/local && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf zlib-${ZLIB_VERSION}* && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/zlib.conf && \
    ldconfig && \
    dpkg --remove --force-depends zlib1g

RUN echo    "    built:" $(date) >> /etc/motd \
    && echo "    branch: " $GITBRANCH >> /etc/motd \
    && echo "    gittag: " $GITTAG >> /etc/motd \
    && echo "    commit: " $GITCOMMIT >> /etc/motd \
    && echo >> /etc/motd

# Force-install the later version of libxml2 for security purposes
RUN export LIBXML2_VERSION=2.13.6 \
    && curl -fsSL -o libxml2.tar.xz   "https://download.gnome.org/sources/libxml2/2.13/libxml2-${LIBXML2_VERSION}.tar.xz" \
    && tar -xf libxml2.tar.xz \
    && cd "libxml2-${LIBXML2_VERSION}" \
    && ./configure --prefix=/usr/local --with-zlib --with-lzma --without-python \
    && make -j"$(nproc)" \
    && make install \
    && echo "/usr/local/lib" > /etc/ld.so.conf.d/usr-local.conf \
    && ldconfig

# This removes the older version
RUN dpkg --remove --force-depends libxml2

HEALTHCHECK CMD pgrep "nginx: master process"

ENTRYPOINT ["/docker-entrypoint-waf.sh"]
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
