FROM ollama/ollama:latest 

COPY ./.docker/zscaler_cert.pem /tmp/zscaler.crt
# Add the zscaler certificate to the trusted certs only on local builds
RUN cp /tmp/zscaler.crt /usr/local/share/ca-certificates/zscaler.crt ; update-ca-certificates ;
