FROM cypress/browsers

# Add the zscaler certificate to the trusted certs only on local builds
# NOTE: Cypress build is always local.
# Copy of cert with chain in /app is for npm
COPY ./.docker/zscaler_cert.pem /tmp/zscaler.crt
COPY ./.docker/zscaler_cypress.pem /app/zscaler_chain.pem
RUN cp /tmp/zscaler.crt /usr/local/share/ca-certificates/zscaler.crt ; update-ca-certificates

COPY ./automated_tests/cypress_build /app

WORKDIR /app

# Install cypress. 
RUN NODE_EXTRA_CA_CERTS=/app/zscaler_chain.pem npm install --save-dev cypress



