FROM ubuntu:focal AS build

ARG NEWRELIC_VERSION
ENV NEWRELIC_VERSION ${NEWRELIC_VERSION:-10.0.0.312}
ENV NEWRELIC_NAME newrelic-php5-${NEWRELIC_VERSION}-linux

RUN  apt-get update \
  && apt-get install -y wget \
  && apt-get install -y curl \
  && apt-get install -y sudo \
  && rm -rf /var/lib/apt/lists/*

RUN set -ex; \
        wget -O /tmp/${NEWRELIC_NAME}.tar.gz https://download.newrelic.com/php_agent/archive/${NEWRELIC_VERSION}/${NEWRELIC_NAME}.tar.gz; \
        cd /tmp/; \
        tar -xzf ${NEWRELIC_NAME}.tar.gz; \
        export NR_INSTALL_SILENT=1; \
        ${NEWRELIC_NAME}/newrelic-install install_daemon

RUN curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash
