# Redis version should match what we use in cloud.gov.
FROM redis:6.2

RUN mkdir /etc/redis && chown redis:redis /etc/redis
COPY .docker/src-cache/redis.conf /etc/redis/redis.conf
RUN chown redis:redis /etc/redis/redis.conf

CMD [ "redis-server", "/etc/redis/redis.conf" ]
