FROM node:16.8.0-alpine3.13

RUN apk upgrade --update --no-cache \
    && apk add --no-cache --virtual .persistent-deps \
      ca-certificates \
      curl \
      git \
      openssh \
    && npm install -g gulp-cli git \
    && rm -rf /var/cache/apk/*

WORKDIR /app/themes/custom/usagov/

CMD ["gulp", "start"]
