FROM node:20-alpine
USER root

RUN apk upgrade --update \
    && apk add --no-cache --virtual .persistent-deps \
       jq \
       bash \
       curl \
       nginx

COPY .docker/src-reporter .

RUN chmod +x /createreport.sh \
    && rm /etc/nginx/http.d/default.conf \
    && /usr/sbin/nginx -s reload \
    && npm install -g analytics-reporter

WORKDIR /analytics-reporter
RUN npm install minimist
RUN npm install
WORKDIR /
CMD ["./createreport.sh"]