
### TBD: Use a more determinate tag please
FROM ubuntu:latest

ARG GITBRANCH
ENV GITBRANCH ${GITBRANCH:-none}

ARG GITCOMMIT
ENV GITCOMMIT ${GITCOMMIT:-none}

ARG GITTAG
ENV GITTAG ${GITTAG:-none}

ARG CONTAINERTAG
ENV CONTAINERTAG ${CONTAINERTAG:-none}

ARG BUID=1000
ARG BGID=1000

RUN apt update --allow-unauthenticated \
    && apt-get -y install --no-install-recommends ca-certificates pv openssh-client sshpass wget gnupg2 \
    && wget --user-agent="Mozilla" --no-check-certificate -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add - \
    && echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list \
    && apt update \
    && apt-get -y install \
    cf8-cli \
    curl \
    jq \
    moreutils \
    pv \
    tar \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*

COPY .docker/src-cfevents/etc /etc
COPY .docker/src-cfevents/opt /opt

CMD ["/bin/bash"]
