# Args are defined in the Dockerfile before the FROM command.
# Using these args will cause an image to be created with node, chrome, firefox and edge.
# Node will be installed regardless. The rest will not be installed unless a version is specified.
# See https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md for
# links to the supported versions and more details. 
ARG NODE_VERSION='20.11.0'
ARG CYPRESS_VERSION='13.6.6'
ARG CHROME_VERSION='121.0.6167.184-1'
ARG EDGE_VERSION='121.0.2277.128-1'
ARG FIREFOX_VERSION='123.0'
# ARG YARN_VERSION='1.22.19'


FROM cypress/factory

# Add the zscaler certificate to the trusted certs only on local builds
# NOTE: Cypress build is always local. 
COPY .docker/zscaler_cert.pem /tmp/zscaler.crt
RUN cp /tmp/zscaler.crt /usr/local/share/ca-certificates/zscaler.crt ; update-ca-certificates

COPY ./automated_tests/cypress_build /app

WORKDIR /app

RUN npm install --save-dev cypress



