#!/usr/bin/env bash

SPACE=$1
VERSION="1.0"

if [ x$SPACE = x ]; then
   SPACE=$(echo $VCAP_APPLICATION | jq -r '.space_name')
fi

source ~/.profile $SPACE callwait &> /dev/null

waitTimeFile="waittime.json"

# echo "Getting access token."
tokenResponse=$(
  curl -s -X POST https://login.$CALL_CENTER_ENVIRONMENT/oauth/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials&client_id=$CALL_CENTER_CLIENT_ID&client_secret=$CALL_CENTER_CLIENT_SECRET"
)
token=$(echo "$tokenResponse" | jq -r '.access_token')

# echo "Getting en wait time."
enWaitTimeResponse=$(
  curl -s -X GET https://api.$CALL_CENTER_ENVIRONMENT/api/v2/routing/queues/$CALL_CENTER_EN_QUEUE_ID/mediatypes/call/estimatedwaittime \
          -H "Authorization:Bearer $token"
);
enWaitTime=$(echo "$enWaitTimeResponse" | jq -r '.results[].estimatedWaitTimeSeconds')

# echo "Getting en chat wait time."
enChatWaitTimeResponse=$(
  curl -s -X GET https://api.$CALL_CENTER_ENVIRONMENT/api/v2/routing/queues/$CALL_CENTER_EN_QUEUE_ID/mediatypes/chat/estimatedwaittime \
          -H "Authorization:Bearer $token"
);
enChatWaitTime=$(echo "$enChatWaitTimeResponse" | jq -r '.results[].estimatedWaitTimeSeconds')

# echo "Getting sp wait time."
spWaitTimeResponse=$(
  curl -s -X GET https://api.$CALL_CENTER_ENVIRONMENT/api/v2/routing/queues/$CALL_CENTER_SP_QUEUE_ID/mediatypes/call/estimatedwaittime \
          -H "Authorization:Bearer $token"
);
spWaitTime=$(echo "$spWaitTimeResponse" | jq -r '.results[].estimatedWaitTimeSeconds')

# echo "Getting sp chat wait time."
spChatWaitTimeResponse=$(
  curl -s -X GET https://api.$CALL_CENTER_ENVIRONMENT/api/v2/routing/queues/$CALL_CENTER_SP_QUEUE_ID/mediatypes/chat/estimatedwaittime \
          -H "Authorization:Bearer $token"
);
spChatWaitTime=$(echo "$spChatWaitTimeResponse" | jq -r '.results[].estimatedWaitTimeSeconds')

timestamp=$(date +%s)
combinedWaitTimes='{
  "call": {
    "estimatedWaitTimeSeconds": {
      "en": '$enWaitTime',
      "sp": '$spWaitTime'
    }
  },
  "chat": {
    "estimatedWaitTimeSeconds": {
      "en": '$enChatWaitTime',
      "sp": '$spChatWaitTime'
    }
  },
  "timestamp": '$timestamp'
}'

# echo "Setting wait time file."
# echo "$combinedWaitTimes" >&2
echo "$combinedWaitTimes" > $waitTimeFile

# Upload file to S3 bucket
# echo "uploading waittime.json to S3."
aws_cp waittime.json s3://$S3_BUCKET/$VERSION/waittime.json
