#!/bin/sh

SPACE=${1:-dr}
if [ x$SPACE = x ]; then
   SPACE=$(echo $VCAP_APPLICATION | jq -r '.space_name')
fi

. ~/.profile $SPACE &> /dev/null

echo CF_API                 $CF_API
echo CF_USERNAME            $CF_USERNAME
echo
echo S3_BUCKET              $S3_BUCKET
echo S3_ENDPOINT            $S3_ENDPOINT
echo
cf -v
echo
cf t
