#!/usr/bin/env bash

TASKSDIR=/tmp/tasks/run
mkdir -p $TASKSDIR

TASKNAME=${1}
if [ x"$TASKNAME" = x ]; then
  echo "No task provided on the commandline. No action taken"
  exit 3
fi
shift

TASKPID=${1}
TASKLOCK="$TASKSDIR/$TASKNAME"

echo "Clean task: $TASKNAME / $TASKPID"

rm -f $TASKLOCK/$TASKPID
PIDS=$(ls $TASKLOCK)
if [ -z "$PIDS" ]; then
  rmdir "$TASKLOCK"
fi

exit 0
