#!/usr/bin/env bash

TASKSDIR=/tmp/tasks/run
mkdir -p $TASKSDIR

TASKTIMEOUT=$1
if [ x$TASKTIMEOUT = x ]; then
  echo "Please provide a positive integer as the first argument.  This is the number of minutes to wait before breaking a lock"
  exit 3
fi
shift

TASKNAME=${1}
if [ x"$TASKNAME" = x ]; then
  echo "No task provided on the commandline. No action taken"
  exit 3
fi
shift

TASKLOCK="$TASKSDIR/$TASKNAME"

# Assuming we have permissions in /tmp, a failure indicates that $TASKLOCK already exists,
# meaning another instance of this script is still running, or failed w/o clearing the lock
# In either case, we exit.  If the lock is stale, we remove it.

if ! mkdir "$TASKLOCK" &> /dev/null; then

  OLDLOCK=$(find "$TASKLOCK" -mmin +$TASKTIMEOUT)

  if [ x"$OLDLOCK" != x ]; then
    echo "Removing stale lock ('$TASKLOCK' is > $TASKTIMEOUT minutes old): '$OLDLOCK'"
    rmdir "$TASKLOCK"
    exit 2
  fi
  echo "$TASKNAME appears to be running already - no action taken."
  exit 1
fi

exit 0
