#!/usr/bin/env bash

TASKSDIR=/tmp/tasks/run
mkdir -p $TASKSDIR

TASKTIMEOUT=$1
if [ x$TASKTIMEOUT = x ]; then
  echo "Please provide a positive integer as the first argument.\
 This is the number of minutes to wait before breaking a lock,\
 if there is no running process associated with the task."
  exit 3
fi
shift

TASKNAME=${1}
if [ x"$TASKNAME" = x ]; then
  echo "No task provided on the commandline. No action taken"
  exit 3
fi
shift

TASKPID=${1}

echo "Task check $TASKNAME / $TASKTIMEOUT / $TASKPID"

TASKLOCK="$TASKSDIR/$TASKNAME"

# Assuming we have permissions in /tmp, a failure indicates that $TASKLOCK already exists,
# meaning another instance of this script is still running, or failed w/o clearing the lock
# In either case, we exit.  If the lock is stale, we remove it.

if ! mkdir "$TASKLOCK" &> /dev/null; then

  lastpid=$(ls -t1 $TASKLOCK | head -n1)

  if [ -n "$lastpid" ]; then
    if ps $lastpid &> /dev/null; then
      echo "$TASKNAME appears to be running since: $FILETIME"
      exit 1
    else
      echo "Removing stale PID file from $TASKLOCK"
      rm $TASKLOCK/$lastpid
      exit 1
    fi
  fi

  OLDLOCK=$(find "$TASKLOCK" -mmin +$TASKTIMEOUT)

  if [ x"$OLDLOCK" != x ]; then
    echo "Removing stale lock ('$TASKLOCK' is > $TASKTIMEOUT minutes old): '$OLDLOCK'"
    rmdir "$TASKLOCK"
    exit 2
  fi
  echo "$TASKNAME appears to be running already - no action taken."
  exit 1
fi

touch $TASKLOCK/$TASKPID

exit 0
