<?php

use Drupal\Core\Form\FormStateInterface;

function usa_admin_styles_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'usa_admin_styles/mylib';
}

/**
 * Attaches a library to only the node forms. This covers the add and edit forms for nodes.
 */
function usa_admin_styles_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // The accordionButtonSubmitFix library suppresses form submit events from accordion buttons in
  // rich text editor previews. This was not an issue with ckeditor 4 (which implemented previews
  // in an iframe), but is a problem in ckeditor 5 -- all preview content is within the node
  // add/edit form, so button elements in the preview will submit the form by default.
  $form['#attached']['library'][] = 'usa_admin_styles/accordionButtonSubmitFix';
  if ($form_id === 'node_basic_page_edit_form' || $form_id === 'node_basic_page_form') {
    $form['#attached']['library'][] = 'usa_admin_styles/benefitsCategoryLanguageFilter';
  }
}
