<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK() for page templates.
 *
 * Attaches the mylib library to all admin pages.
 *
 * @param array<string, mixed> $variables
 */
function usa_admin_styles_preprocess_page(array &$variables): void {
  $variables['#attached']['library'][] = 'usa_admin_styles/mylib';
}

/**
 * Attaches a library to only the node forms. This covers the add and edit forms for nodes.
 *
 * @param array<string, mixed> $form
 */
function usa_admin_styles_form_node_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // The accordionButtonSubmitFix library suppresses form submit events from accordion buttons in
  // rich text editor previews. This was not an issue with ckeditor 4 (which implemented previews
  // in an iframe), but is a problem in ckeditor 5 -- all preview content is within the node
  // add/edit form, so button elements in the preview will submit the form by default.
  $form['#attached']['library'][] = 'usa_admin_styles/accordionButtonSubmitFix';
  if ($form_id === 'node_basic_page_edit_form' || $form_id === 'node_basic_page_form') {
    $form['#attached']['library'][] = 'usa_admin_styles/benefitsCategoryLanguageFilter';
  }
}
