#!/bin/sh
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 11: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 12: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 13: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 14: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 15: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 16: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 17: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 18: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 19: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 20: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 21: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 22: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 23: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 24: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 25: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 26: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 27: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 28: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 29: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 20: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 31: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 32: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 33: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 34: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 35: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 36: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 37: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 38: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 39: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 40: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 41: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 42: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 43: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 44: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 45: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 46: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 47: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 48: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 49: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 50: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 51: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 52: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 53: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 54: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 55: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 56: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 57: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 58: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 59: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 60: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 61: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 62: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 63: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 64: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 65: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 66: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 67: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 68: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 69: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 70: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 71: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 72: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 73: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 74: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 75: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 76: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 77: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 78: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 79: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 80: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 81: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 82: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 83: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 84: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 85: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 86: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 87: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 88: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 89: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 90: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 91: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 92: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 93: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 94: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 95: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 96: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 97: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 98: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 99: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 100: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 101: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 102: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 103: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 104: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 105: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 106: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 107: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 108: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 109: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 110: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 111: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 112: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 113: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 114: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 115: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 116: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 117: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 118: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 119: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 120: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 121: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 122: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 123: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 124: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 125: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 126: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 127: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 128: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 129: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 120: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 131: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 132: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 133: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 134: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 135: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 136: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 137: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 138: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 139: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 140: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 141: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 142: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 143: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 144: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 145: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 146: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 147: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 148: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 149: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 150: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 151: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 152: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 153: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 154: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 155: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 156: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 157: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 158: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 159: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 160: I finished\n" localhost &