# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - (cd .. && cp -r build scheduled_publish)
          - composer create-project drupal-composer/drupal-project:8.x-dev -s dev drupal
          - mkdir drupal/web/modules/contrib
          - mv ../scheduled_publish drupal/web/modules/contrib
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - (cd drupal/web/modules/contrib/scheduled_publish && ../../../../vendor/bin/phpunit)
  branches:
    '8.x-*':
      - step:
          name: Build and test
          caches:
            - composer
          script:
            - (cd .. && cp -r build scheduled_publish)
            - composer create-project drupal-composer/drupal-project:8.x-dev -s dev drupal
            - mkdir drupal/web/modules/contrib
            - mv ../scheduled_publish drupal/web/modules/contrib
            - export PATH="$HOME/.composer/vendor/bin:$PATH"
            - (cd drupal/web/modules/contrib/scheduled_publish && ../../../../vendor/bin/phpunit)
      - step:
          name: Push dev to drupal.org
          script:
            - git remote add drupal git@git.drupal.org:project/scheduled_publish.git
            - git config --global push.default matching
            - git config --global user.name "SaschaHannes"
            - git push drupal $BITBUCKET_BRANCH
  tags:
    '*':
      - step:
          name: Pushing tags to drupal.org
          script:
            - git remote add drupal git@git.drupal.org:project/scheduled_publish.git
            - git config --global push.default matching
            - git config --global user.name "SaschaHannes"
            - git push drupal $BITBUCKET_BRANCH --tags
