<?php

/**
 * @file
 * Use proprocess for html twig.
 */

use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\node\Entity\Node;

/**
 * Description message.
 *
 * @param mixed $variables
 *   Self described.
 * @param mixed $hook
 *   Self described.
 */


function usagov_top_navigation_menu_page_attachments(array &$page) {
  // $test_str2 = "testing isabel can pass vars2";
  // kint($test_str2);
  $page['#attached']['library'][] = 'usagov_top_navigation_menu/usagov_top_navigation_menu_js';

  $top_nav_menu = usagov_top_navigation_menu_get_top_nav();
  $page['#attached']['drupalSettings']['top_nav_menu'] = $top_nav_menu;
}

function usagov_top_navigation_menu_get_top_nav() {
  $menu_parameters = new MenuTreeParameters();
  $tree = \Drupal::menuTree()->load('top-navigation', $menu_parameters);
  $topnav = array();

  foreach ($tree as $item) {
    $menu_path = $item->link->getUrlObject()->toString();
    $menu_id = $item->link->getDescription();
    $menu_item = [$menu_path => $menu_id];
    array_push($topnav, $menu_item);
  }
  // kint($topnav);
  return $topnav;
}

