<?php

/**
 * @file
 * Auto-delete orphaned synonyms and language toggles when deleting
 * Federal Directory Records.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\ConfirmFormInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_form_alter.
 *
 * @param array<string, mixed> $form
 **/

function usa_orphaned_entities_form_alter(array &$form, FormStateInterface &$form_state, string $form_id): void {
  if (str_contains($form_id, 'delete_form')) {
    // This is called on all delete form alters. Ensure we can get
    // an entity otherwise bail early.
    $delForm = $form_state->getFormObject();
    if (!method_exists($delForm, 'getEntity')) {
      return;
    }

    $entity = $delForm->getEntity();
    if (!$entity) {
      return;
    }

    $reference_data = usa_orphaned_entities_get_reference_data($entity);

    $markup = '';
    if ($delForm instanceof ConfirmFormInterface) {
      $markup = "<div class=\"default-message\">" .
        $delForm->getDescription() . "</div>";
    }
    else {
      $markup = '<div class="default-message">This action cannot be undone.</div>';
    }
    $segway = "T"; // It's a joke about powered scooters.
    $additional = "";

    if (!empty($reference_data)) {
      if (!empty($reference_data['delete'])) {
        $additional .= "<br />" . PHP_EOL;
        $additional .= "<div class=\"entity-delete\">";
        $additional .= "<span>Deleting this entity will also delete the following entities:</span>" . PHP_EOL;
        $additional .= "<ul>" . PHP_EOL;
        foreach ($reference_data['delete']['references'] as $reference_delete) {
          $additional .= "<li>" . $reference_delete->getType()
            . ": <a href=\"/node/" . $reference_delete->id()
            . "\" target=\"_blank\">" . $reference_delete->title->value
            . " (" . $reference_delete->id() . ")</a></li>" . PHP_EOL;
        }
        $additional .= "</ul></div>" . PHP_EOL;
        $segway = "Additionally, t";
      }

      if (!empty($reference_data['clear'])) {
        $additional .= "<br />" . PHP_EOL;
        $additional .= "<div class=\"entity-remove\">";
        $additional .= "<span>" . $segway . "he following entities will have their entity references cleared:</span>" . PHP_EOL;
        $additional .= "<ul>" . PHP_EOL;

        foreach ($reference_data['clear']['references'] as $reference_clear) {
          $additional .= "<li>" . $reference_clear->getType() . ": <a href=\"/node/" . $reference_clear->id() . "\" target=\"_blank\">" . $reference_clear->title->value . " (" . $reference_clear->id() . ")</a></li>" . PHP_EOL;
        }

        $additional .= "</ul></div>" . PHP_EOL;
        if (!empty($reference_delete)) {
          $segway = 'Finally, t';
        }
        else {
          $segway = "Additionally, t";
        }
      }

      if (!empty($reference_data['skip'])) {
        $additional .= "<br />" . PHP_EOL;
        $additional .= "<div class=\"entity-skip\">";
        $additional .= "<span>" . $segway . "he following entity references will be skipped and leave orphans:</span>" . PHP_EOL;
        $additional .= "<ul>" . PHP_EOL;

        foreach ($reference_data['skip']['references'] as $reference_skip) {
          $id = $reference_skip->id();
          $type = $reference_skip->getEntityTypeId();
          $title = $reference_skip->label();

          switch (get_class($reference_skip)) {
            case Node::class:
              $type = $reference_skip->getType();
              break;

            case Term::class:
              $type = $reference_skip->getEntityTypeId() . ' / ' . $reference_skip->bundle();
              break;
          }

          // Some entities, like paragraphs, don't have a link template
          // which makes call to toUrl() fail.
          if ($reference_skip->hasLinkTemplate('canonical')) {
            $additional .= sprintf(
              '<li><a href="%s" target="_blank">%s: %s (%d)</a></li>' . PHP_EOL,
              $reference_skip->toUrl()->toString(), $type, Html::escape($title), $id
            );
          }
          else {
            $additional .= sprintf(
              '<li>%s: %s (%d)</li>' . PHP_EOL,
              $type, Html::escape($title), $id
            );
          }
        }

        $additional .= "</ul></div>" . PHP_EOL;
      }
    }

    $form['description']['#markup'] = t($markup . $additional);
  }
}

/**
 * Implements hook_entity_predelete.
 */
function usa_orphaned_entities_entity_predelete(EntityInterface $entity): void {
  $reference_data = usa_orphaned_entities_get_reference_data($entity);
  if (!empty($reference_data)) {
    if (!empty($reference_data['delete'])) {
      foreach ($reference_data['delete']['references'] as $reference_delete) {
        $reference_delete->delete();
      }
    }
    if (!empty($reference_data['clear'])) {
      foreach ($reference_data['clear']['references'] as $reference_clear) {
        $field = $reference_data['clear']['metadata']['field'];
        unset($reference_clear->$field);
        $reference_clear->save();
      }
    }
  }

}

/**
 * Grab the data from all references from the entity being deleted.
 *
 * @return array<string, mixed>
 **/
function usa_orphaned_entities_get_reference_data(EntityInterface $deleting_entity): array {
  $entityTypeManager = \Drupal::service('entity_type.manager');
  $config = \Drupal::config('orphaned_entities.settings');

  $reference_data = [];
  $deleted_id = $deleting_entity->id();
  $deleted_entity_type = $deleting_entity->getEntityTypeId();

  $entity_references = $entityTypeManager
    ->getStorage('field_storage_config')
    ->loadByProperties([
      'type' => 'entity_reference',
    ]);

  foreach ($entity_references as $entity_reference) {
    $bundles = $entity_reference->getBundles();

    foreach ($bundles as $bundle) {
      $reference_field = $entity_reference->getName();
      // We do need to know what kind of entity this field belongs to.
      // getTargetEntityTypeId() answers "as a field, which entity type
      // are you/ attached to?" It should not matter if $reference_field
      // is not attached to the same entity type that we are deleting.
      $entity_type = $entity_reference->getTargetEntityTypeId();

      // Instead, we must look at the "target_type" setting to check
      // if $reference_field can select other entities like the
      // current $deleted_entity_type.
      $target_type = $entity_reference->getSetting('target_type');
      if ($target_type !== $deleted_entity_type) {
        continue;
      }

      $query = $entityTypeManager
        ->getStorage("$entity_type")
        ->getQuery()
        ->condition("$reference_field", "$deleted_id")
        ->accessCheck(TRUE);
      $results = $query->execute();
      $references = $entityTypeManager
        ->getStorage("$entity_type")
        ->loadMultiple($results);

      $action = $config->get('orphaned_entities.' . $bundle . '_' . $reference_field);
      if (!empty($references)) {
        foreach ($references as $reference) {
          switch ($action) {
            case 'delete':
              $reference_data['delete']['references'][$reference->id()] = $reference;
              $reference_data['delete']['metadata'] = [
                'field' => $reference_field,
                'type' => $entity_type,
              ];
              break;

            case 'clear':
              $reference_data['clear']['references'][$reference->id()] = $reference;
              $reference_data['clear']['metadata'] = [
                'field' => $reference_field,
                'type' => $entity_type,
              ];
              break;

            case 'skip':
              $reference_data['skip']['references'][$reference->id()] = $reference;
              $reference_data['skip']['metadata'] = [
                'field' => $reference_field,
                'type' => $entity_type,
              ];
              break;

            default:
              $reference_data['skip']['references'][$reference->id()] = $reference;
              $reference_data['skip']['metadata'] = [
                'field' => $reference_field,
                'type' => $entity_type,
              ];
          }
        }
      }
    }
  }

  return $reference_data;
}
