name: Stage A11Y Regression Tests

on: workflow_dispatch

permissions:
  contents: read

jobs:
  run-regression-tests:
    name: run-regression-tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set env
        run: echo "CYPRESS_BASE_URL=https://beta-stage.usa.gov/" >> $GITHUB_ENV
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          working-directory: automated_tests/cypress_build
          project: ../e2e-cypress
          spec: ../e2e-cypress/cypress/e2e/regression_testing/*.cy.js
