#!/bin/sh
echo "------------------------------STARTING TESTING------------------------------"
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 11: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 12: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 13: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 14: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 15: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 11: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 12: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 13: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 14: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 15: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 11: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 12: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 13: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 14: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 15: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 1: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 2: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 3: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 4: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 5: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 6: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 7: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 8: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 9: I finished\n" localhost &
curl -s -o /dev/null -w "[$(date +'%Y-%m-%d %H:%M:%S')] Attempt 10: I finished\n" localhost &